try again with just !success

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -43,18 +43,18 @@ jobs:
           #failure: ${{toJSON(failure())}}
           #success: ${{toJSON(success())}}
         run: export
-      - name: check step result directly
-        if: ${{ needs.lint.result != 'success' }}
-        run: exit 1
-      - name: A job failed
-        if: ${{ failure() }}
-        run: exit 1
-      - name: The workflow was cancelled
-        if: ${{ cancelled() }}
-        run: exit 1
-      - name: All jobs succeeded
-        if: ${{ success() }}
-        run: echo pass
+#      - name: check step result directly
+#        if: ${{ needs.lint.result != 'success' }}
+#        run: exit 1
+#      - name: A job failed
+#        if: ${{ failure() }}
+#        run: exit 1
+#      - name: The workflow was cancelled
+#        if: ${{ cancelled() }}
+#        run: exit 1
+#      - name: All jobs succeeded
+#        if: ${{ success() }}
+#        run: echo pass
       - name: Not success
         if: ${{ !success() }}
         run: exit 1
